version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/buriti
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



  db:
    image: 'postgres:13.1-alpine'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

      POSTGRES_DB: buritiscript
    volumes:
      - buritiscript-volume:/var/lib/postgresql/data
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "emersonreisdacosta@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "123"
#    ports:
#      - "81:80"
#    depends_on:
#      - db

volumes:
  buritiscript-volume: